/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.persist.app.dis.zk;

import com.ocean.core.common.base.AbstractBaseEntity;

public class ZKAppDetail  extends AbstractBaseEntity{
  
  /**
	 * 
	 */
	  private static final long serialVersionUID = -4271765989630082550L;
	  private int type; // required
	  private  String pkgName; // optional
	  private String appName; // optional
	  private String iconUrl; // optional
	  private String logoUrl; // optional
	  private String fileSize; // optional
	  private String versionCode; // optional
	  private String versionName; // optional
	  private String developer; // optional
	  private String appLanguage; // optional
	  private String minSdkVersion; // optional
	  private String desc; // optional
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public String getPkgName() {
		return pkgName;
	}
	public void setPkgName(String pkgName) {
		this.pkgName = pkgName;
	}
	public String getAppName() {
		return appName;
	}
	public void setAppName(String appName) {
		this.appName = appName;
	}
	public String getIconUrl() {
		return iconUrl;
	}
	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}
	public String getLogoUrl() {
		return logoUrl;
	}
	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}
	public String getFileSize() {
		return fileSize;
	}
	public void setFileSize(String fileSize) {
		this.fileSize = fileSize;
	}
	public String getVersionCode() {
		return versionCode;
	}
	public void setVersionCode(String versionCode) {
		this.versionCode = versionCode;
	}
	public String getVersionName() {
		return versionName;
	}
	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}
	public String getDeveloper() {
		return developer;
	}
	public void setDeveloper(String developer) {
		this.developer = developer;
	}
	public String getAppLanguage() {
		return appLanguage;
	}
	public void setAppLanguage(String appLanguage) {
		this.appLanguage = appLanguage;
	}
	public String getMinSdkVersion() {
		return minSdkVersion;
	}
	public void setMinSdkVersion(String minSdkVersion) {
		this.minSdkVersion = minSdkVersion;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}

}

