/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.persist.app.dis.zk;


import java.util.List;
import java.util.Map;

import com.ocean.persist.app.dis.AppDisResponse;


public class ZKAppRecomReply   implements AppDisResponse{


		  private String requestId;
		  private String errorCode; // required
		  private String errorMsg; // optional
		  private List<ZKAppContent> appDisContent; // optional
		  private Map<String,List<String>> thirdReportLinks; // optional
		  
			public String getErrorCode() {
				return errorCode;
			}
			public void setErrorCode(String errorCode) {
				this.errorCode = errorCode;
			}
			public String getErrorMsg() {
				return errorMsg;
			}
			public void setErrorMsg(String errorMsg) {
				this.errorMsg = errorMsg;
			}
			public List<ZKAppContent> getAppDisContent() {
				return appDisContent;
			}
			public void setAppDisContent(List<ZKAppContent> appDisContent) {
				this.appDisContent = appDisContent;
			}
			public Map<String, List<String>> getThirdReportLinks() {
				return thirdReportLinks;
			}
			public void setThirdReportLinks(Map<String, List<String>> thirdReportLinks) {
				this.thirdReportLinks = thirdReportLinks;
			}
			public String getRequestId() {
				return requestId;
			}
			public void setRequestId(String requestId) {
				this.requestId = requestId;
			}


}

