/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.persist.app.dis.zk;

import com.ocean.core.common.base.AbstractBaseEntity;


public class ZKDeviceInfo extends AbstractBaseEntity{
	  
	  /**
	 * 
	 */
	private static final long serialVersionUID = -2517991350436552253L;
	private String imei; // optional
	  private String os; // optional
	  private String osversion; // optional
	  private String phonemodel; // optional
	  private String mobile; // optional
	  private String aaid; // optional
	  private String adid; // optional
	  private String idfa; // optional
	  private String brandId; // optional
	  private String brandName; // optional
	  private int deviceHeight; // optional
	  private int deviceWidth; // optional
	  private String mac; // optional
	  private String imsi; // optional
	  private String serialNo; // optional
	  private String dip; // optional
	  private String dpi; // optional
	  private String osVerName; // optional
		public String getImei() {
			return imei;
		}
		public void setImei(String imei) {
			this.imei = imei;
		}
		public String getOs() {
			return os;
		}
		public void setOs(String os) {
			this.os = os;
		}
		public String getOsversion() {
			return osversion;
		}
		public void setOsversion(String osversion) {
			this.osversion = osversion;
		}
		public String getPhonemodel() {
			return phonemodel;
		}
		public void setPhonemodel(String phonemodel) {
			this.phonemodel = phonemodel;
		}
		public String getMobile() {
			return mobile;
		}
		public void setMobile(String mobile) {
			this.mobile = mobile;
		}
		public String getAaid() {
			return aaid;
		}
		public void setAaid(String aaid) {
			this.aaid = aaid;
		}
		public String getAdid() {
			return adid;
		}
		public void setAdid(String adid) {
			this.adid = adid;
		}
		public String getIdfa() {
			return idfa;
		}
		public void setIdfa(String idfa) {
			this.idfa = idfa;
		}
		public String getBrandId() {
			return brandId;
		}
		public void setBrandId(String brandId) {
			this.brandId = brandId;
		}
		public String getBrandName() {
			return brandName;
		}
		public void setBrandName(String brandName) {
			this.brandName = brandName;
		}
		public int getDeviceHeight() {
			return deviceHeight;
		}
		public void setDeviceHeight(int deviceHeight) {
			this.deviceHeight = deviceHeight;
		}
		public int getDeviceWidth() {
			return deviceWidth;
		}
		public void setDeviceWidth(int deviceWidth) {
			this.deviceWidth = deviceWidth;
		}
		public String getMac() {
			return mac;
		}
		public void setMac(String mac) {
			this.mac = mac;
		}
		public String getImsi() {
			return imsi;
		}
		public void setImsi(String imsi) {
			this.imsi = imsi;
		}
		public String getSerialNo() {
			return serialNo;
		}
		public void setSerialNo(String serialNo) {
			this.serialNo = serialNo;
		}
		public String getDip() {
			return dip;
		}
		public void setDip(String dip) {
			this.dip = dip;
		}
		public String getDpi() {
			return dpi;
		}
		public void setDpi(String dpi) {
			this.dpi = dpi;
		}
		public String getOsVerName() {
			return osVerName;
		}
		public void setOsVerName(String osVerName) {
			this.osVerName = osVerName;
		}
		
		  

}

