/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.persist.app.dis.zk;

import java.util.List;

import com.ocean.core.common.base.AbstractBaseEntity;

public class ZKInterParam   extends AbstractBaseEntity{


    /**
	 * 
	 */
	  private static final long serialVersionUID = -315531928724037539L;
	  private String keyWord; // optional
	  private String hotWord; // optional
	  private List<ZKExtData> requiredParam; // optional
	  
		public String getKeyWord() {
			return keyWord;
		}
		public void setKeyWord(String keyWord) {
			this.keyWord = keyWord;
		}
		public String getHotWord() {
			return hotWord;
		}
		public void setHotWord(String hotWord) {
			this.hotWord = hotWord;
		}
		public List<ZKExtData> getRequiredParam() {
			return requiredParam;
		}
		public void setRequiredParam(List<ZKExtData> requiredParam) {
			this.requiredParam = requiredParam;
		}

}

