// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enumType.proto

package com.ocean.persist.api.proxy.adhub;

public final class EnumType {
  private EnumType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 请求来源
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.SrcType}
   */
  public enum SrcType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>SRC_UNKNOWN = 0;</code>
     */
    SRC_UNKNOWN(0),
    /**
     * <pre>
     * 移动应用
     * </pre>
     *
     * <code>SRC_APP = 1;</code>
     */
    SRC_APP(1),
    /**
     * <pre>
     * 移动Web
     * </pre>
     *
     * <code>SRC_WAP = 2;</code>
     */
    SRC_WAP(2),
    /**
     * <pre>
     * PC
     * </pre>
     *
     * <code>SRC_PC = 3;</code>
     */
    SRC_PC(3),
    /**
     * <code>SRC_TEST = 4;</code>
     */
    SRC_TEST(4),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>SRC_UNKNOWN = 0;</code>
     */
    public static final int SRC_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 移动应用
     * </pre>
     *
     * <code>SRC_APP = 1;</code>
     */
    public static final int SRC_APP_VALUE = 1;
    /**
     * <pre>
     * 移动Web
     * </pre>
     *
     * <code>SRC_WAP = 2;</code>
     */
    public static final int SRC_WAP_VALUE = 2;
    /**
     * <pre>
     * PC
     * </pre>
     *
     * <code>SRC_PC = 3;</code>
     */
    public static final int SRC_PC_VALUE = 3;
    /**
     * <code>SRC_TEST = 4;</code>
     */
    public static final int SRC_TEST_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SrcType valueOf(int value) {
      return forNumber(value);
    }

    public static SrcType forNumber(int value) {
      switch (value) {
        case 0: return SRC_UNKNOWN;
        case 1: return SRC_APP;
        case 2: return SRC_WAP;
        case 3: return SRC_PC;
        case 4: return SRC_TEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SrcType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SrcType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SrcType>() {
            public SrcType findValueByNumber(int number) {
              return SrcType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(0);
    }

    private static final SrcType[] VALUES = values();

    public static SrcType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SrcType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.SrcType)
  }

  /**
   * <pre>
   * 广告请求类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.ReqType}
   */
  public enum ReqType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>REQ_UNKNOWN = 0;</code>
     */
    REQ_UNKNOWN(0),
    /**
     * <pre>
     * 广告请求
     * </pre>
     *
     * <code>REQ_AD = 1;</code>
     */
    REQ_AD(1),
    /**
     * <pre>
     * 广告WIFI预加载
     * </pre>
     *
     * <code>REQ_WIFI_PRELOAD = 2;</code>
     */
    REQ_WIFI_PRELOAD(2),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>REQ_UNKNOWN = 0;</code>
     */
    public static final int REQ_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 广告请求
     * </pre>
     *
     * <code>REQ_AD = 1;</code>
     */
    public static final int REQ_AD_VALUE = 1;
    /**
     * <pre>
     * 广告WIFI预加载
     * </pre>
     *
     * <code>REQ_WIFI_PRELOAD = 2;</code>
     */
    public static final int REQ_WIFI_PRELOAD_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReqType valueOf(int value) {
      return forNumber(value);
    }

    public static ReqType forNumber(int value) {
      switch (value) {
        case 0: return REQ_UNKNOWN;
        case 1: return REQ_AD;
        case 2: return REQ_WIFI_PRELOAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReqType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReqType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReqType>() {
            public ReqType findValueByNumber(int number) {
              return ReqType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(1);
    }

    private static final ReqType[] VALUES = values();

    public static ReqType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReqType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.ReqType)
  }

  /**
   * <pre>
   * 广告日志类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.LogType}
   */
  public enum LogType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>LOG_UNKNOWN = 0;</code>
     */
    LOG_UNKNOWN(0),
    /**
     * <pre>
     * 广告效果日志 view, click, convert, action log
     * </pre>
     *
     * <code>LOG_RESP = 1;</code>
     */
    LOG_RESP(1),
    /**
     * <pre>
     * 用户标签
     * </pre>
     *
     * <code>LOG_CUSTOMER_TAG = 2;</code>
     */
    LOG_CUSTOMER_TAG(2),
    /**
     * <pre>
     * 统计信息
     * </pre>
     *
     * <code>LOG_STATISTIC = 3;</code>
     */
    LOG_STATISTIC(3),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>LOG_UNKNOWN = 0;</code>
     */
    public static final int LOG_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 广告效果日志 view, click, convert, action log
     * </pre>
     *
     * <code>LOG_RESP = 1;</code>
     */
    public static final int LOG_RESP_VALUE = 1;
    /**
     * <pre>
     * 用户标签
     * </pre>
     *
     * <code>LOG_CUSTOMER_TAG = 2;</code>
     */
    public static final int LOG_CUSTOMER_TAG_VALUE = 2;
    /**
     * <pre>
     * 统计信息
     * </pre>
     *
     * <code>LOG_STATISTIC = 3;</code>
     */
    public static final int LOG_STATISTIC_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LogType valueOf(int value) {
      return forNumber(value);
    }

    public static LogType forNumber(int value) {
      switch (value) {
        case 0: return LOG_UNKNOWN;
        case 1: return LOG_RESP;
        case 2: return LOG_CUSTOMER_TAG;
        case 3: return LOG_STATISTIC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LogType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogType>() {
            public LogType findValueByNumber(int number) {
              return LogType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(2);
    }

    private static final LogType[] VALUES = values();

    public static LogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LogType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.LogType)
  }

  /**
   * <pre>
   * 广告交互类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.ReactType}
   */
  public enum ReactType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REACT_UNKNOWN = 0;</code>
     */
    REACT_UNKNOWN(0),
    /**
     * <pre>
     * 曝光
     * </pre>
     *
     * <code>REACT_VIEW = 1;</code>
     */
    REACT_VIEW(1),
    /**
     * <pre>
     * 点击
     * </pre>
     *
     * <code>REACT_CLICK = 2;</code>
     */
    REACT_CLICK(2),
    /**
     * <pre>
     * 转化
     * </pre>
     *
     * <code>REACT_CONV = 3;</code>
     */
    REACT_CONV(3),
    /**
     * <pre>
     * 行为
     * </pre>
     *
     * <code>REACT_ACTION = 4;</code>
     */
    REACT_ACTION(4),
    ;

    /**
     * <code>REACT_UNKNOWN = 0;</code>
     */
    public static final int REACT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 曝光
     * </pre>
     *
     * <code>REACT_VIEW = 1;</code>
     */
    public static final int REACT_VIEW_VALUE = 1;
    /**
     * <pre>
     * 点击
     * </pre>
     *
     * <code>REACT_CLICK = 2;</code>
     */
    public static final int REACT_CLICK_VALUE = 2;
    /**
     * <pre>
     * 转化
     * </pre>
     *
     * <code>REACT_CONV = 3;</code>
     */
    public static final int REACT_CONV_VALUE = 3;
    /**
     * <pre>
     * 行为
     * </pre>
     *
     * <code>REACT_ACTION = 4;</code>
     */
    public static final int REACT_ACTION_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReactType valueOf(int value) {
      return forNumber(value);
    }

    public static ReactType forNumber(int value) {
      switch (value) {
        case 0: return REACT_UNKNOWN;
        case 1: return REACT_VIEW;
        case 2: return REACT_CLICK;
        case 3: return REACT_CONV;
        case 4: return REACT_ACTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReactType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReactType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReactType>() {
            public ReactType findValueByNumber(int number) {
              return ReactType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(3);
    }

    private static final ReactType[] VALUES = values();

    public static ReactType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReactType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.ReactType)
  }

  /**
   * <pre>
   * 自定义标签类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.TagType}
   */
  public enum TagType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TAG_UNKNOWN = 0;</code>
     */
    TAG_UNKNOWN(0),
    /**
     * <pre>
     * 自定义标签
     * </pre>
     *
     * <code>TAG_CUSTOMER = 1;</code>
     */
    TAG_CUSTOMER(1),
    ;

    /**
     * <code>TAG_UNKNOWN = 0;</code>
     */
    public static final int TAG_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 自定义标签
     * </pre>
     *
     * <code>TAG_CUSTOMER = 1;</code>
     */
    public static final int TAG_CUSTOMER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TagType valueOf(int value) {
      return forNumber(value);
    }

    public static TagType forNumber(int value) {
      switch (value) {
        case 0: return TAG_UNKNOWN;
        case 1: return TAG_CUSTOMER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TagType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TagType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TagType>() {
            public TagType findValueByNumber(int number) {
              return TagType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(4);
    }

    private static final TagType[] VALUES = values();

    public static TagType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TagType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.TagType)
  }

  /**
   * <pre>
   * 平台类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.PlatformType}
   */
  public enum PlatformType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>PLATFORM_UNKNOWN = 0;</code>
     */
    PLATFORM_UNKNOWN(0),
    /**
     * <pre>
     * iOS 
     * </pre>
     *
     * <code>PLATFORM_IOS = 1;</code>
     */
    PLATFORM_IOS(1),
    /**
     * <pre>
     * android
     * </pre>
     *
     * <code>PLATFORM_ANDROID = 2;</code>
     */
    PLATFORM_ANDROID(2),
    /**
     * <pre>
     * 其他
     * </pre>
     *
     * <code>PLATFORM_OTHER = 3;</code>
     */
    PLATFORM_OTHER(3),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>PLATFORM_UNKNOWN = 0;</code>
     */
    public static final int PLATFORM_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * iOS 
     * </pre>
     *
     * <code>PLATFORM_IOS = 1;</code>
     */
    public static final int PLATFORM_IOS_VALUE = 1;
    /**
     * <pre>
     * android
     * </pre>
     *
     * <code>PLATFORM_ANDROID = 2;</code>
     */
    public static final int PLATFORM_ANDROID_VALUE = 2;
    /**
     * <pre>
     * 其他
     * </pre>
     *
     * <code>PLATFORM_OTHER = 3;</code>
     */
    public static final int PLATFORM_OTHER_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlatformType valueOf(int value) {
      return forNumber(value);
    }

    public static PlatformType forNumber(int value) {
      switch (value) {
        case 0: return PLATFORM_UNKNOWN;
        case 1: return PLATFORM_IOS;
        case 2: return PLATFORM_ANDROID;
        case 3: return PLATFORM_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformType>() {
            public PlatformType findValueByNumber(int number) {
              return PlatformType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(5);
    }

    private static final PlatformType[] VALUES = values();

    public static PlatformType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.PlatformType)
  }

  /**
   * <pre>
   * 设备类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEVICE_UNKNOWN = 0;</code>
     */
    DEVICE_UNKNOWN(0),
    /**
     * <pre>
     * 移动电话
     * </pre>
     *
     * <code>DEVICE_PHONE = 1;</code>
     */
    DEVICE_PHONE(1),
    /**
     * <pre>
     * 平板
     * </pre>
     *
     * <code>DEVICE_FLAT = 2;</code>
     */
    DEVICE_FLAT(2),
    /**
     * <pre>
     * 穿戴设备
     * </pre>
     *
     * <code>DEVICE_WEAR = 3;</code>
     */
    DEVICE_WEAR(3),
    /**
     * <pre>
     * PC
     * </pre>
     *
     * <code>DEVICE_PC = 4;</code>
     */
    DEVICE_PC(4),
    /**
     * <pre>
     * 其他设备
     * </pre>
     *
     * <code>DEVICE_OTHER = 5;</code>
     */
    DEVICE_OTHER(5),
    ;

    /**
     * <code>DEVICE_UNKNOWN = 0;</code>
     */
    public static final int DEVICE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 移动电话
     * </pre>
     *
     * <code>DEVICE_PHONE = 1;</code>
     */
    public static final int DEVICE_PHONE_VALUE = 1;
    /**
     * <pre>
     * 平板
     * </pre>
     *
     * <code>DEVICE_FLAT = 2;</code>
     */
    public static final int DEVICE_FLAT_VALUE = 2;
    /**
     * <pre>
     * 穿戴设备
     * </pre>
     *
     * <code>DEVICE_WEAR = 3;</code>
     */
    public static final int DEVICE_WEAR_VALUE = 3;
    /**
     * <pre>
     * PC
     * </pre>
     *
     * <code>DEVICE_PC = 4;</code>
     */
    public static final int DEVICE_PC_VALUE = 4;
    /**
     * <pre>
     * 其他设备
     * </pre>
     *
     * <code>DEVICE_OTHER = 5;</code>
     */
    public static final int DEVICE_OTHER_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DeviceType valueOf(int value) {
      return forNumber(value);
    }

    public static DeviceType forNumber(int value) {
      switch (value) {
        case 0: return DEVICE_UNKNOWN;
        case 1: return DEVICE_PHONE;
        case 2: return DEVICE_FLAT;
        case 3: return DEVICE_WEAR;
        case 4: return DEVICE_PC;
        case 5: return DEVICE_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DeviceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(6);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DeviceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.DeviceType)
  }

  /**
   * <pre>
   * 网络环境类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.NetType}
   */
  public enum NetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NET_UNKNOWN = 0;</code>
     */
    NET_UNKNOWN(0),
    /**
     * <code>NET_3G = 1;</code>
     */
    NET_3G(1),
    /**
     * <code>NET_4G = 2;</code>
     */
    NET_4G(2),
    /**
     * <code>NET_5G = 3;</code>
     */
    NET_5G(3),
    /**
     * <code>NET_WIFI = 4;</code>
     */
    NET_WIFI(4),
    /**
     * <code>NET_OTHER = 5;</code>
     */
    NET_OTHER(5),
    /**
     * <code>NET_2G = 6;</code>
     */
    NET_2G(6),
    ;

    /**
     * <code>NET_UNKNOWN = 0;</code>
     */
    public static final int NET_UNKNOWN_VALUE = 0;
    /**
     * <code>NET_3G = 1;</code>
     */
    public static final int NET_3G_VALUE = 1;
    /**
     * <code>NET_4G = 2;</code>
     */
    public static final int NET_4G_VALUE = 2;
    /**
     * <code>NET_5G = 3;</code>
     */
    public static final int NET_5G_VALUE = 3;
    /**
     * <code>NET_WIFI = 4;</code>
     */
    public static final int NET_WIFI_VALUE = 4;
    /**
     * <code>NET_OTHER = 5;</code>
     */
    public static final int NET_OTHER_VALUE = 5;
    /**
     * <code>NET_2G = 6;</code>
     */
    public static final int NET_2G_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NetType valueOf(int value) {
      return forNumber(value);
    }

    public static NetType forNumber(int value) {
      switch (value) {
        case 0: return NET_UNKNOWN;
        case 1: return NET_3G;
        case 2: return NET_4G;
        case 3: return NET_5G;
        case 4: return NET_WIFI;
        case 5: return NET_OTHER;
        case 6: return NET_2G;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NetType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NetType>() {
            public NetType findValueByNumber(int number) {
              return NetType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(7);
    }

    private static final NetType[] VALUES = values();

    public static NetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NetType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.NetType)
  }

  /**
   * <pre>
   * 网络运营商类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.IspType}
   */
  public enum IspType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>ISP_UNKNOWN = 0;</code>
     */
    ISP_UNKNOWN(0),
    /**
     * <pre>
     * 移动
     * </pre>
     *
     * <code>ISP_CN_MOBILE = 1;</code>
     */
    ISP_CN_MOBILE(1),
    /**
     * <pre>
     * 联通
     * </pre>
     *
     * <code>ISP_CN_UNICOM = 2;</code>
     */
    ISP_CN_UNICOM(2),
    /**
     * <pre>
     * 电信
     * </pre>
     *
     * <code>ISP_CN_TEL = 3;</code>
     */
    ISP_CN_TEL(3),
    /**
     * <pre>
     * 其他
     * </pre>
     *
     * <code>ISP_OTHER = 4;</code>
     */
    ISP_OTHER(4),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>ISP_UNKNOWN = 0;</code>
     */
    public static final int ISP_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 移动
     * </pre>
     *
     * <code>ISP_CN_MOBILE = 1;</code>
     */
    public static final int ISP_CN_MOBILE_VALUE = 1;
    /**
     * <pre>
     * 联通
     * </pre>
     *
     * <code>ISP_CN_UNICOM = 2;</code>
     */
    public static final int ISP_CN_UNICOM_VALUE = 2;
    /**
     * <pre>
     * 电信
     * </pre>
     *
     * <code>ISP_CN_TEL = 3;</code>
     */
    public static final int ISP_CN_TEL_VALUE = 3;
    /**
     * <pre>
     * 其他
     * </pre>
     *
     * <code>ISP_OTHER = 4;</code>
     */
    public static final int ISP_OTHER_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static IspType valueOf(int value) {
      return forNumber(value);
    }

    public static IspType forNumber(int value) {
      switch (value) {
        case 0: return ISP_UNKNOWN;
        case 1: return ISP_CN_MOBILE;
        case 2: return ISP_CN_UNICOM;
        case 3: return ISP_CN_TEL;
        case 4: return ISP_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IspType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        IspType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IspType>() {
            public IspType findValueByNumber(int number) {
              return IspType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(8);
    }

    private static final IspType[] VALUES = values();

    public static IspType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private IspType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.IspType)
  }

  /**
   * <pre>
   * 屏幕方向
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.ScreenDirectionType}
   */
  public enum ScreenDirectionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>SCREEN_DIRECTION_UNKOWN = 0;</code>
     */
    SCREEN_DIRECTION_UNKOWN(0),
    /**
     * <pre>
     * 竖屏
     * </pre>
     *
     * <code>PORTRAIT = 1;</code>
     */
    PORTRAIT(1),
    /**
     * <pre>
     * 横屏
     * </pre>
     *
     * <code>LANDSCAPE = 2;</code>
     */
    LANDSCAPE(2),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>SCREEN_DIRECTION_UNKOWN = 0;</code>
     */
    public static final int SCREEN_DIRECTION_UNKOWN_VALUE = 0;
    /**
     * <pre>
     * 竖屏
     * </pre>
     *
     * <code>PORTRAIT = 1;</code>
     */
    public static final int PORTRAIT_VALUE = 1;
    /**
     * <pre>
     * 横屏
     * </pre>
     *
     * <code>LANDSCAPE = 2;</code>
     */
    public static final int LANDSCAPE_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ScreenDirectionType valueOf(int value) {
      return forNumber(value);
    }

    public static ScreenDirectionType forNumber(int value) {
      switch (value) {
        case 0: return SCREEN_DIRECTION_UNKOWN;
        case 1: return PORTRAIT;
        case 2: return LANDSCAPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ScreenDirectionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ScreenDirectionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ScreenDirectionType>() {
            public ScreenDirectionType findValueByNumber(int number) {
              return ScreenDirectionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(9);
    }

    private static final ScreenDirectionType[] VALUES = values();

    public static ScreenDirectionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ScreenDirectionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.ScreenDirectionType)
  }

  /**
   * <pre>
   * 广告位类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.AdpType}
   */
  public enum AdpType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>ADP_UNKNOWN = 0;</code>
     */
    ADP_UNKNOWN(0),
    /**
     * <pre>
     * 激励视频
     * </pre>
     *
     * <code>ADP_IVIDEO = 1;</code>
     */
    ADP_IVIDEO(1),
    /**
     * <pre>
     * 开屏
     * </pre>
     *
     * <code>ADP_LOADING = 2;</code>
     */
    ADP_LOADING(2),
    /**
     * <pre>
     * 插屏
     * </pre>
     *
     * <code>ADP_TABLE = 3;</code>
     */
    ADP_TABLE(3),
    /**
     * <pre>
     * BANNER
     * </pre>
     *
     * <code>ADP_BANNER = 4;</code>
     */
    ADP_BANNER(4),
    /**
     * <pre>
     * 自定义
     * </pre>
     *
     * <code>ADP_CUSTOMER = 5;</code>
     */
    ADP_CUSTOMER(5),
    /**
     * <pre>
     * 原生
     * </pre>
     *
     * <code>ADP_NATIVE = 6;</code>
     */
    ADP_NATIVE(6),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>ADP_UNKNOWN = 0;</code>
     */
    public static final int ADP_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 激励视频
     * </pre>
     *
     * <code>ADP_IVIDEO = 1;</code>
     */
    public static final int ADP_IVIDEO_VALUE = 1;
    /**
     * <pre>
     * 开屏
     * </pre>
     *
     * <code>ADP_LOADING = 2;</code>
     */
    public static final int ADP_LOADING_VALUE = 2;
    /**
     * <pre>
     * 插屏
     * </pre>
     *
     * <code>ADP_TABLE = 3;</code>
     */
    public static final int ADP_TABLE_VALUE = 3;
    /**
     * <pre>
     * BANNER
     * </pre>
     *
     * <code>ADP_BANNER = 4;</code>
     */
    public static final int ADP_BANNER_VALUE = 4;
    /**
     * <pre>
     * 自定义
     * </pre>
     *
     * <code>ADP_CUSTOMER = 5;</code>
     */
    public static final int ADP_CUSTOMER_VALUE = 5;
    /**
     * <pre>
     * 原生
     * </pre>
     *
     * <code>ADP_NATIVE = 6;</code>
     */
    public static final int ADP_NATIVE_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AdpType valueOf(int value) {
      return forNumber(value);
    }

    public static AdpType forNumber(int value) {
      switch (value) {
        case 0: return ADP_UNKNOWN;
        case 1: return ADP_IVIDEO;
        case 2: return ADP_LOADING;
        case 3: return ADP_TABLE;
        case 4: return ADP_BANNER;
        case 5: return ADP_CUSTOMER;
        case 6: return ADP_NATIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AdpType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AdpType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AdpType>() {
            public AdpType findValueByNumber(int number) {
              return AdpType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(10);
    }

    private static final AdpType[] VALUES = values();

    public static AdpType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AdpType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.AdpType)
  }

  /**
   * <pre>
   * 素材类型/素材渲染方式
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.RenderType}
   */
  public enum RenderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>RENDER_UNKNOWN = 0;</code>
     */
    RENDER_UNKNOWN(0),
    /**
     * <pre>
     * 素材为视频 URL，接收方负责播放
     * </pre>
     *
     * <code>RENDER_VIDEO = 1;</code>
     */
    RENDER_VIDEO(1),
    /**
     * <pre>
     * 素材为图片 URL，接收方负责展示 展示时长的参数
     * </pre>
     *
     * <code>RENDER_PIC = 2;</code>
     */
    RENDER_PIC(2),
    /**
     * <pre>
     * 素材为H5，接收方使用WebView展示
     * </pre>
     *
     * <code>RENDER_H5 = 3;</code>
     */
    RENDER_H5(3),
    /**
     * <pre>
     * 素材为JSON，接收方负责展示
     * </pre>
     *
     * <code>RENDER_JSON = 4;</code>
     */
    RENDER_JSON(4),
    /**
     * <pre>
     * 素材为 VAST_VIDEO, contentSlot.content 为 VAST_VIDEO 内容(XML)
     * </pre>
     *
     * <code>RENDER_VAST_VIDEO = 5;</code>
     */
    RENDER_VAST_VIDEO(5),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>RENDER_UNKNOWN = 0;</code>
     */
    public static final int RENDER_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 素材为视频 URL，接收方负责播放
     * </pre>
     *
     * <code>RENDER_VIDEO = 1;</code>
     */
    public static final int RENDER_VIDEO_VALUE = 1;
    /**
     * <pre>
     * 素材为图片 URL，接收方负责展示 展示时长的参数
     * </pre>
     *
     * <code>RENDER_PIC = 2;</code>
     */
    public static final int RENDER_PIC_VALUE = 2;
    /**
     * <pre>
     * 素材为H5，接收方使用WebView展示
     * </pre>
     *
     * <code>RENDER_H5 = 3;</code>
     */
    public static final int RENDER_H5_VALUE = 3;
    /**
     * <pre>
     * 素材为JSON，接收方负责展示
     * </pre>
     *
     * <code>RENDER_JSON = 4;</code>
     */
    public static final int RENDER_JSON_VALUE = 4;
    /**
     * <pre>
     * 素材为 VAST_VIDEO, contentSlot.content 为 VAST_VIDEO 内容(XML)
     * </pre>
     *
     * <code>RENDER_VAST_VIDEO = 5;</code>
     */
    public static final int RENDER_VAST_VIDEO_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RenderType valueOf(int value) {
      return forNumber(value);
    }

    public static RenderType forNumber(int value) {
      switch (value) {
        case 0: return RENDER_UNKNOWN;
        case 1: return RENDER_VIDEO;
        case 2: return RENDER_PIC;
        case 3: return RENDER_H5;
        case 4: return RENDER_JSON;
        case 5: return RENDER_VAST_VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RenderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RenderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RenderType>() {
            public RenderType findValueByNumber(int number) {
              return RenderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(11);
    }

    private static final RenderType[] VALUES = values();

    public static RenderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RenderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.RenderType)
  }

  /**
   * <pre>
   * 性别
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.GenderType}
   */
  public enum GenderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>GENDER_UNKNOWN = 0;</code>
     */
    GENDER_UNKNOWN(0),
    /**
     * <pre>
     * 男性
     * </pre>
     *
     * <code>GENDER_MALE = 1;</code>
     */
    GENDER_MALE(1),
    /**
     * <pre>
     * 女性
     * </pre>
     *
     * <code>GENDER_FEMALE = 2;</code>
     */
    GENDER_FEMALE(2),
    /**
     * <pre>
     * 其他
     * </pre>
     *
     * <code>GENDER_OTHER = 3;</code>
     */
    GENDER_OTHER(3),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>GENDER_UNKNOWN = 0;</code>
     */
    public static final int GENDER_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 男性
     * </pre>
     *
     * <code>GENDER_MALE = 1;</code>
     */
    public static final int GENDER_MALE_VALUE = 1;
    /**
     * <pre>
     * 女性
     * </pre>
     *
     * <code>GENDER_FEMALE = 2;</code>
     */
    public static final int GENDER_FEMALE_VALUE = 2;
    /**
     * <pre>
     * 其他
     * </pre>
     *
     * <code>GENDER_OTHER = 3;</code>
     */
    public static final int GENDER_OTHER_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GenderType valueOf(int value) {
      return forNumber(value);
    }

    public static GenderType forNumber(int value) {
      switch (value) {
        case 0: return GENDER_UNKNOWN;
        case 1: return GENDER_MALE;
        case 2: return GENDER_FEMALE;
        case 3: return GENDER_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GenderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GenderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GenderType>() {
            public GenderType findValueByNumber(int number) {
              return GenderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(12);
    }

    private static final GenderType[] VALUES = values();

    public static GenderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GenderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.GenderType)
  }

  /**
   * <pre>
   * Deal类型
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.DealType}
   */
  public enum DealType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>DEAL_UNKNOWN = 0;</code>
     */
    DEAL_UNKNOWN(0),
    /**
     * <pre>
     * 保价
     * </pre>
     *
     * <code>DEAL_PD = 1;</code>
     */
    DEAL_PD(1),
    /**
     * <pre>
     *保价保量
     * </pre>
     *
     * <code>DEAL_PDB = 2;</code>
     */
    DEAL_PDB(2),
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>DEAL_OTHER = 3;</code>
     */
    DEAL_OTHER(3),
    ;

    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>DEAL_UNKNOWN = 0;</code>
     */
    public static final int DEAL_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 保价
     * </pre>
     *
     * <code>DEAL_PD = 1;</code>
     */
    public static final int DEAL_PD_VALUE = 1;
    /**
     * <pre>
     *保价保量
     * </pre>
     *
     * <code>DEAL_PDB = 2;</code>
     */
    public static final int DEAL_PDB_VALUE = 2;
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>DEAL_OTHER = 3;</code>
     */
    public static final int DEAL_OTHER_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DealType valueOf(int value) {
      return forNumber(value);
    }

    public static DealType forNumber(int value) {
      switch (value) {
        case 0: return DEAL_UNKNOWN;
        case 1: return DEAL_PD;
        case 2: return DEAL_PDB;
        case 3: return DEAL_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DealType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DealType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DealType>() {
            public DealType findValueByNumber(int number) {
              return DealType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(13);
    }

    private static final DealType[] VALUES = values();

    public static DealType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DealType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.DealType)
  }

  /**
   * <pre>
   * BidAtType
   * </pre>
   *
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.BidATType}
   */
  public enum BidATType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>BID_AT_UNKNOWN = 0;</code>
     */
    BID_AT_UNKNOWN(0),
    /**
     * <pre>
     *first price
     * </pre>
     *
     * <code>BID_AT_First_Price = 1;</code>
     */
    BID_AT_First_Price(1),
    /**
     * <pre>
     *second price
     * </pre>
     *
     * <code>BID_AT_Second_Price = 2;</code>
     */
    BID_AT_Second_Price(2),
    /**
     * <pre>
     *Fix Price from bidfloor
     * </pre>
     *
     * <code>BID_AD_Fix_From_Bidfloor = 3;</code>
     */
    BID_AD_Fix_From_Bidfloor(3),
    ;

    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>BID_AT_UNKNOWN = 0;</code>
     */
    public static final int BID_AT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     *first price
     * </pre>
     *
     * <code>BID_AT_First_Price = 1;</code>
     */
    public static final int BID_AT_First_Price_VALUE = 1;
    /**
     * <pre>
     *second price
     * </pre>
     *
     * <code>BID_AT_Second_Price = 2;</code>
     */
    public static final int BID_AT_Second_Price_VALUE = 2;
    /**
     * <pre>
     *Fix Price from bidfloor
     * </pre>
     *
     * <code>BID_AD_Fix_From_Bidfloor = 3;</code>
     */
    public static final int BID_AD_Fix_From_Bidfloor_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BidATType valueOf(int value) {
      return forNumber(value);
    }

    public static BidATType forNumber(int value) {
      switch (value) {
        case 0: return BID_AT_UNKNOWN;
        case 1: return BID_AT_First_Price;
        case 2: return BID_AT_Second_Price;
        case 3: return BID_AD_Fix_From_Bidfloor;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BidATType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BidATType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BidATType>() {
            public BidATType findValueByNumber(int number) {
              return BidATType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(14);
    }

    private static final BidATType[] VALUES = values();

    public static BidATType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BidATType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.BidATType)
  }

  /**
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.MaterialType}
   */
  public enum MaterialType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知类型
     * </pre>
     *
     * <code>MT_UNKNOWN = 0;</code>
     */
    MT_UNKNOWN(0),
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>MT_PIC = 1;</code>
     */
    MT_PIC(1),
    /**
     * <pre>
     * 文字
     * </pre>
     *
     * <code>MT_TEXT = 2;</code>
     */
    MT_TEXT(2),
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>MT_VIDEO = 3;</code>
     */
    MT_VIDEO(3),
    ;

    /**
     * <pre>
     *未知类型
     * </pre>
     *
     * <code>MT_UNKNOWN = 0;</code>
     */
    public static final int MT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>MT_PIC = 1;</code>
     */
    public static final int MT_PIC_VALUE = 1;
    /**
     * <pre>
     * 文字
     * </pre>
     *
     * <code>MT_TEXT = 2;</code>
     */
    public static final int MT_TEXT_VALUE = 2;
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>MT_VIDEO = 3;</code>
     */
    public static final int MT_VIDEO_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MaterialType valueOf(int value) {
      return forNumber(value);
    }

    public static MaterialType forNumber(int value) {
      switch (value) {
        case 0: return MT_UNKNOWN;
        case 1: return MT_PIC;
        case 2: return MT_TEXT;
        case 3: return MT_VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MaterialType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MaterialType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MaterialType>() {
            public MaterialType findValueByNumber(int number) {
              return MaterialType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(15);
    }

    private static final MaterialType[] VALUES = values();

    public static MaterialType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MaterialType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.MaterialType)
  }

  /**
   * Protobuf enum {@code com.ocean.persist.api.proxy.adhub.MaterialSubType}
   */
  public enum MaterialSubType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知类型
     * </pre>
     *
     * <code>MST_UNKOWN = 0;</code>
     */
    MST_UNKOWN(0),
    /**
     * <pre>
     * 静态图
     * </pre>
     *
     * <code>MST_PIC_STATIC = 1;</code>
     */
    MST_PIC_STATIC(1),
    /**
     * <pre>
     * 动态图
     * </pre>
     *
     * <code>MST_PIC_DYNAMIC = 2;</code>
     */
    MST_PIC_DYNAMIC(2),
    /**
     * <pre>
     * 图标
     * </pre>
     *
     * <code>MST_PIC_ICON = 3;</code>
     */
    MST_PIC_ICON(3),
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>MST_TEXT_HEADLINE = 10;</code>
     */
    MST_TEXT_HEADLINE(10),
    /**
     * <pre>
     * 子标题
     * </pre>
     *
     * <code>MST_TEXT_SUB_HEADLINE = 11;</code>
     */
    MST_TEXT_SUB_HEADLINE(11),
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>MST_TEXT_DESC = 12;</code>
     */
    MST_TEXT_DESC(12),
    /**
     * <pre>
     * 正文
     * </pre>
     *
     * <code>MST_TEXT_BODY = 13;</code>
     */
    MST_TEXT_BODY(13),
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>MST_TEXT_TAG = 14;</code>
     */
    MST_TEXT_TAG(14),
    /**
     * <pre>
     * URL
     * </pre>
     *
     * <code>MST_TEXT_URL = 15;</code>
     */
    MST_TEXT_URL(15),
    /**
     * <pre>
     * mpeg
     * </pre>
     *
     * <code>MSG_VIDEO_MPEG = 16;</code>
     */
    MSG_VIDEO_MPEG(16),
    /**
     * <pre>
     * vast
     * </pre>
     *
     * <code>MSG_VIDEO_VAST = 17;</code>
     */
    MSG_VIDEO_VAST(17),
    /**
     * <pre>
     * avi
     * </pre>
     *
     * <code>MSG_VIDEO_AVI = 18;</code>
     */
    MSG_VIDEO_AVI(18),
    ;

    /**
     * <pre>
     * 未知类型
     * </pre>
     *
     * <code>MST_UNKOWN = 0;</code>
     */
    public static final int MST_UNKOWN_VALUE = 0;
    /**
     * <pre>
     * 静态图
     * </pre>
     *
     * <code>MST_PIC_STATIC = 1;</code>
     */
    public static final int MST_PIC_STATIC_VALUE = 1;
    /**
     * <pre>
     * 动态图
     * </pre>
     *
     * <code>MST_PIC_DYNAMIC = 2;</code>
     */
    public static final int MST_PIC_DYNAMIC_VALUE = 2;
    /**
     * <pre>
     * 图标
     * </pre>
     *
     * <code>MST_PIC_ICON = 3;</code>
     */
    public static final int MST_PIC_ICON_VALUE = 3;
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>MST_TEXT_HEADLINE = 10;</code>
     */
    public static final int MST_TEXT_HEADLINE_VALUE = 10;
    /**
     * <pre>
     * 子标题
     * </pre>
     *
     * <code>MST_TEXT_SUB_HEADLINE = 11;</code>
     */
    public static final int MST_TEXT_SUB_HEADLINE_VALUE = 11;
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>MST_TEXT_DESC = 12;</code>
     */
    public static final int MST_TEXT_DESC_VALUE = 12;
    /**
     * <pre>
     * 正文
     * </pre>
     *
     * <code>MST_TEXT_BODY = 13;</code>
     */
    public static final int MST_TEXT_BODY_VALUE = 13;
    /**
     * <pre>
     * 标签
     * </pre>
     *
     * <code>MST_TEXT_TAG = 14;</code>
     */
    public static final int MST_TEXT_TAG_VALUE = 14;
    /**
     * <pre>
     * URL
     * </pre>
     *
     * <code>MST_TEXT_URL = 15;</code>
     */
    public static final int MST_TEXT_URL_VALUE = 15;
    /**
     * <pre>
     * mpeg
     * </pre>
     *
     * <code>MSG_VIDEO_MPEG = 16;</code>
     */
    public static final int MSG_VIDEO_MPEG_VALUE = 16;
    /**
     * <pre>
     * vast
     * </pre>
     *
     * <code>MSG_VIDEO_VAST = 17;</code>
     */
    public static final int MSG_VIDEO_VAST_VALUE = 17;
    /**
     * <pre>
     * avi
     * </pre>
     *
     * <code>MSG_VIDEO_AVI = 18;</code>
     */
    public static final int MSG_VIDEO_AVI_VALUE = 18;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MaterialSubType valueOf(int value) {
      return forNumber(value);
    }

    public static MaterialSubType forNumber(int value) {
      switch (value) {
        case 0: return MST_UNKOWN;
        case 1: return MST_PIC_STATIC;
        case 2: return MST_PIC_DYNAMIC;
        case 3: return MST_PIC_ICON;
        case 10: return MST_TEXT_HEADLINE;
        case 11: return MST_TEXT_SUB_HEADLINE;
        case 12: return MST_TEXT_DESC;
        case 13: return MST_TEXT_BODY;
        case 14: return MST_TEXT_TAG;
        case 15: return MST_TEXT_URL;
        case 16: return MSG_VIDEO_MPEG;
        case 17: return MSG_VIDEO_VAST;
        case 18: return MSG_VIDEO_AVI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MaterialSubType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MaterialSubType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MaterialSubType>() {
            public MaterialSubType findValueByNumber(int number) {
              return MaterialSubType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ocean.persist.api.proxy.adhub.EnumType.getDescriptor().getEnumTypes().get(16);
    }

    private static final MaterialSubType[] VALUES = values();

    public static MaterialSubType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MaterialSubType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ocean.persist.api.proxy.adhub.MaterialSubType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016enumType.proto\022!com.ocean.persist.api." +
      "proxy.adhub*N\n\007SrcType\022\017\n\013SRC_UNKNOWN\020\000\022" +
      "\013\n\007SRC_APP\020\001\022\013\n\007SRC_WAP\020\002\022\n\n\006SRC_PC\020\003\022\014\n" +
      "\010SRC_TEST\020\004*<\n\007ReqType\022\017\n\013REQ_UNKNOWN\020\000\022" +
      "\n\n\006REQ_AD\020\001\022\024\n\020REQ_WIFI_PRELOAD\020\002*Q\n\007Log" +
      "Type\022\017\n\013LOG_UNKNOWN\020\000\022\014\n\010LOG_RESP\020\001\022\024\n\020L" +
      "OG_CUSTOMER_TAG\020\002\022\021\n\rLOG_STATISTIC\020\003*a\n\t" +
      "ReactType\022\021\n\rREACT_UNKNOWN\020\000\022\016\n\nREACT_VI" +
      "EW\020\001\022\017\n\013REACT_CLICK\020\002\022\016\n\nREACT_CONV\020\003\022\020\n" +
      "\014REACT_ACTION\020\004*,\n\007TagType\022\017\n\013TAG_UNKNOW",
      "N\020\000\022\020\n\014TAG_CUSTOMER\020\001*`\n\014PlatformType\022\024\n" +
      "\020PLATFORM_UNKNOWN\020\000\022\020\n\014PLATFORM_IOS\020\001\022\024\n" +
      "\020PLATFORM_ANDROID\020\002\022\022\n\016PLATFORM_OTHER\020\003*" +
      "u\n\nDeviceType\022\022\n\016DEVICE_UNKNOWN\020\000\022\020\n\014DEV" +
      "ICE_PHONE\020\001\022\017\n\013DEVICE_FLAT\020\002\022\017\n\013DEVICE_W" +
      "EAR\020\003\022\r\n\tDEVICE_PC\020\004\022\020\n\014DEVICE_OTHER\020\005*g" +
      "\n\007NetType\022\017\n\013NET_UNKNOWN\020\000\022\n\n\006NET_3G\020\001\022\n" +
      "\n\006NET_4G\020\002\022\n\n\006NET_5G\020\003\022\014\n\010NET_WIFI\020\004\022\r\n\t" +
      "NET_OTHER\020\005\022\n\n\006NET_2G\020\006*_\n\007IspType\022\017\n\013IS" +
      "P_UNKNOWN\020\000\022\021\n\rISP_CN_MOBILE\020\001\022\021\n\rISP_CN",
      "_UNICOM\020\002\022\016\n\nISP_CN_TEL\020\003\022\r\n\tISP_OTHER\020\004" +
      "*O\n\023ScreenDirectionType\022\033\n\027SCREEN_DIRECT" +
      "ION_UNKOWN\020\000\022\014\n\010PORTRAIT\020\001\022\r\n\tLANDSCAPE\020" +
      "\002*|\n\007AdpType\022\017\n\013ADP_UNKNOWN\020\000\022\016\n\nADP_IVI" +
      "DEO\020\001\022\017\n\013ADP_LOADING\020\002\022\r\n\tADP_TABLE\020\003\022\016\n" +
      "\nADP_BANNER\020\004\022\020\n\014ADP_CUSTOMER\020\005\022\016\n\nADP_N" +
      "ATIVE\020\006*y\n\nRenderType\022\022\n\016RENDER_UNKNOWN\020" +
      "\000\022\020\n\014RENDER_VIDEO\020\001\022\016\n\nRENDER_PIC\020\002\022\r\n\tR" +
      "ENDER_H5\020\003\022\017\n\013RENDER_JSON\020\004\022\025\n\021RENDER_VA" +
      "ST_VIDEO\020\005*V\n\nGenderType\022\022\n\016GENDER_UNKNO",
      "WN\020\000\022\017\n\013GENDER_MALE\020\001\022\021\n\rGENDER_FEMALE\020\002" +
      "\022\020\n\014GENDER_OTHER\020\003*G\n\010DealType\022\020\n\014DEAL_U" +
      "NKNOWN\020\000\022\013\n\007DEAL_PD\020\001\022\014\n\010DEAL_PDB\020\002\022\016\n\nD" +
      "EAL_OTHER\020\003*n\n\tBidATType\022\022\n\016BID_AT_UNKNO" +
      "WN\020\000\022\026\n\022BID_AT_First_Price\020\001\022\027\n\023BID_AT_S" +
      "econd_Price\020\002\022\034\n\030BID_AD_Fix_From_Bidfloo" +
      "r\020\003*E\n\014MaterialType\022\016\n\nMT_UNKNOWN\020\000\022\n\n\006M" +
      "T_PIC\020\001\022\013\n\007MT_TEXT\020\002\022\014\n\010MT_VIDEO\020\003*\223\002\n\017M" +
      "aterialSubType\022\016\n\nMST_UNKOWN\020\000\022\022\n\016MST_PI" +
      "C_STATIC\020\001\022\023\n\017MST_PIC_DYNAMIC\020\002\022\020\n\014MST_P",
      "IC_ICON\020\003\022\025\n\021MST_TEXT_HEADLINE\020\n\022\031\n\025MST_" +
      "TEXT_SUB_HEADLINE\020\013\022\021\n\rMST_TEXT_DESC\020\014\022\021" +
      "\n\rMST_TEXT_BODY\020\r\022\020\n\014MST_TEXT_TAG\020\016\022\020\n\014M" +
      "ST_TEXT_URL\020\017\022\022\n\016MSG_VIDEO_MPEG\020\020\022\022\n\016MSG" +
      "_VIDEO_VAST\020\021\022\021\n\rMSG_VIDEO_AVI\020\022"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
