/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.lbs.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements org.apache.thrift.TEnum {
  RC_SUCCESS(0),
  RC_PARAM_ERROR(-1),
  RC_INTER_ERROR(-2),
  RC_UNKNOW_ERROR(-3);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return RC_SUCCESS;
      case -1:
        return RC_PARAM_ERROR;
      case -2:
        return RC_INTER_ERROR;
      case -3:
        return RC_UNKNOW_ERROR;
      default:
        return null;
    }
  }
}
