/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.app.dis.proxy.thrift.entity;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;

import javax.annotation.Generated;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-8-14")
public class DeviceInfo implements org.apache.thrift.TBase<DeviceInfo, DeviceInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DeviceInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DeviceInfo");

  private static final org.apache.thrift.protocol.TField IMEI_FIELD_DESC = new org.apache.thrift.protocol.TField("imei", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField OS_FIELD_DESC = new org.apache.thrift.protocol.TField("os", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OSVERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("osversion", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PHONEMODEL_FIELD_DESC = new org.apache.thrift.protocol.TField("phonemodel", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField MOBILE_FIELD_DESC = new org.apache.thrift.protocol.TField("mobile", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField AAID_FIELD_DESC = new org.apache.thrift.protocol.TField("aaid", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField ADID_FIELD_DESC = new org.apache.thrift.protocol.TField("adid", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField IDFA_FIELD_DESC = new org.apache.thrift.protocol.TField("idfa", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField BRAND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("brandId", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField BRAND_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("brandName", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField DEVICE_HEIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("deviceHeight", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField DEVICE_WIDTH_FIELD_DESC = new org.apache.thrift.protocol.TField("deviceWidth", org.apache.thrift.protocol.TType.I32, (short)12);
  private static final org.apache.thrift.protocol.TField MAC_FIELD_DESC = new org.apache.thrift.protocol.TField("mac", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField IMSI_FIELD_DESC = new org.apache.thrift.protocol.TField("imsi", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField SERIAL_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("serialNo", org.apache.thrift.protocol.TType.STRING, (short)15);
  private static final org.apache.thrift.protocol.TField DIP_FIELD_DESC = new org.apache.thrift.protocol.TField("dip", org.apache.thrift.protocol.TType.STRING, (short)16);
  private static final org.apache.thrift.protocol.TField DPI_FIELD_DESC = new org.apache.thrift.protocol.TField("dpi", org.apache.thrift.protocol.TType.STRING, (short)17);
  private static final org.apache.thrift.protocol.TField OS_VER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("osVerName", org.apache.thrift.protocol.TType.STRING, (short)18);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DeviceInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DeviceInfoTupleSchemeFactory());
  }

  public String imei; // optional
  public String os; // optional
  public String osversion; // optional
  public String phonemodel; // optional
  public String mobile; // optional
  public String aaid; // optional
  public String adid; // optional
  public String idfa; // optional
  public String brandId; // optional
  public String brandName; // optional
  public int deviceHeight; // optional
  public int deviceWidth; // optional
  public String mac; // optional
  public String imsi; // optional
  public String serialNo; // optional
  public String dip; // optional
  public String dpi; // optional
  public String osVerName; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IMEI((short)1, "imei"),
    OS((short)2, "os"),
    OSVERSION((short)3, "osversion"),
    PHONEMODEL((short)4, "phonemodel"),
    MOBILE((short)5, "mobile"),
    AAID((short)6, "aaid"),
    ADID((short)7, "adid"),
    IDFA((short)8, "idfa"),
    BRAND_ID((short)9, "brandId"),
    BRAND_NAME((short)10, "brandName"),
    DEVICE_HEIGHT((short)11, "deviceHeight"),
    DEVICE_WIDTH((short)12, "deviceWidth"),
    MAC((short)13, "mac"),
    IMSI((short)14, "imsi"),
    SERIAL_NO((short)15, "serialNo"),
    DIP((short)16, "dip"),
    DPI((short)17, "dpi"),
    OS_VER_NAME((short)18, "osVerName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IMEI
          return IMEI;
        case 2: // OS
          return OS;
        case 3: // OSVERSION
          return OSVERSION;
        case 4: // PHONEMODEL
          return PHONEMODEL;
        case 5: // MOBILE
          return MOBILE;
        case 6: // AAID
          return AAID;
        case 7: // ADID
          return ADID;
        case 8: // IDFA
          return IDFA;
        case 9: // BRAND_ID
          return BRAND_ID;
        case 10: // BRAND_NAME
          return BRAND_NAME;
        case 11: // DEVICE_HEIGHT
          return DEVICE_HEIGHT;
        case 12: // DEVICE_WIDTH
          return DEVICE_WIDTH;
        case 13: // MAC
          return MAC;
        case 14: // IMSI
          return IMSI;
        case 15: // SERIAL_NO
          return SERIAL_NO;
        case 16: // DIP
          return DIP;
        case 17: // DPI
          return DPI;
        case 18: // OS_VER_NAME
          return OS_VER_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DEVICEHEIGHT_ISSET_ID = 0;
  private static final int __DEVICEWIDTH_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.IMEI,_Fields.OS,_Fields.OSVERSION,_Fields.PHONEMODEL,_Fields.MOBILE,_Fields.AAID,_Fields.ADID,_Fields.IDFA,_Fields.BRAND_ID,_Fields.BRAND_NAME,_Fields.DEVICE_HEIGHT,_Fields.DEVICE_WIDTH,_Fields.MAC,_Fields.IMSI,_Fields.SERIAL_NO,_Fields.DIP,_Fields.DPI,_Fields.OS_VER_NAME};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IMEI, new org.apache.thrift.meta_data.FieldMetaData("imei", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OS, new org.apache.thrift.meta_data.FieldMetaData("os", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OSVERSION, new org.apache.thrift.meta_data.FieldMetaData("osversion", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PHONEMODEL, new org.apache.thrift.meta_data.FieldMetaData("phonemodel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MOBILE, new org.apache.thrift.meta_data.FieldMetaData("mobile", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AAID, new org.apache.thrift.meta_data.FieldMetaData("aaid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ADID, new org.apache.thrift.meta_data.FieldMetaData("adid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IDFA, new org.apache.thrift.meta_data.FieldMetaData("idfa", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BRAND_ID, new org.apache.thrift.meta_data.FieldMetaData("brandId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BRAND_NAME, new org.apache.thrift.meta_data.FieldMetaData("brandName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEVICE_HEIGHT, new org.apache.thrift.meta_data.FieldMetaData("deviceHeight", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DEVICE_WIDTH, new org.apache.thrift.meta_data.FieldMetaData("deviceWidth", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAC, new org.apache.thrift.meta_data.FieldMetaData("mac", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMSI, new org.apache.thrift.meta_data.FieldMetaData("imsi", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SERIAL_NO, new org.apache.thrift.meta_data.FieldMetaData("serialNo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DIP, new org.apache.thrift.meta_data.FieldMetaData("dip", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DPI, new org.apache.thrift.meta_data.FieldMetaData("dpi", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OS_VER_NAME, new org.apache.thrift.meta_data.FieldMetaData("osVerName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DeviceInfo.class, metaDataMap);
  }

  public DeviceInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DeviceInfo(DeviceInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetOs()) {
      this.os = other.os;
    }
    if (other.isSetOsversion()) {
      this.osversion = other.osversion;
    }
    if (other.isSetPhonemodel()) {
      this.phonemodel = other.phonemodel;
    }
    if (other.isSetMobile()) {
      this.mobile = other.mobile;
    }
    if (other.isSetAaid()) {
      this.aaid = other.aaid;
    }
    if (other.isSetAdid()) {
      this.adid = other.adid;
    }
    if (other.isSetIdfa()) {
      this.idfa = other.idfa;
    }
    if (other.isSetBrandId()) {
      this.brandId = other.brandId;
    }
    if (other.isSetBrandName()) {
      this.brandName = other.brandName;
    }
    this.deviceHeight = other.deviceHeight;
    this.deviceWidth = other.deviceWidth;
    if (other.isSetMac()) {
      this.mac = other.mac;
    }
    if (other.isSetImsi()) {
      this.imsi = other.imsi;
    }
    if (other.isSetSerialNo()) {
      this.serialNo = other.serialNo;
    }
    if (other.isSetDip()) {
      this.dip = other.dip;
    }
    if (other.isSetDpi()) {
      this.dpi = other.dpi;
    }
    if (other.isSetOsVerName()) {
      this.osVerName = other.osVerName;
    }
  }

  public DeviceInfo deepCopy() {
    return new DeviceInfo(this);
  }

  
  public void clear() {
    this.imei = null;
    this.os = null;
    this.osversion = null;
    this.phonemodel = null;
    this.mobile = null;
    this.aaid = null;
    this.adid = null;
    this.idfa = null;
    this.brandId = null;
    this.brandName = null;
    setDeviceHeightIsSet(false);
    this.deviceHeight = 0;
    setDeviceWidthIsSet(false);
    this.deviceWidth = 0;
    this.mac = null;
    this.imsi = null;
    this.serialNo = null;
    this.dip = null;
    this.dpi = null;
    this.osVerName = null;
  }

  public String getImei() {
    return this.imei;
  }

  public DeviceInfo setImei(String imei) {
    this.imei = imei;
    return this;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been assigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getOs() {
    return this.os;
  }

  public DeviceInfo setOs(String os) {
    this.os = os;
    return this;
  }

  public void unsetOs() {
    this.os = null;
  }

  /** Returns true if field os is set (has been assigned a value) and false otherwise */
  public boolean isSetOs() {
    return this.os != null;
  }

  public void setOsIsSet(boolean value) {
    if (!value) {
      this.os = null;
    }
  }

  public String getOsversion() {
    return this.osversion;
  }

  public DeviceInfo setOsversion(String osversion) {
    this.osversion = osversion;
    return this;
  }

  public void unsetOsversion() {
    this.osversion = null;
  }

  /** Returns true if field osversion is set (has been assigned a value) and false otherwise */
  public boolean isSetOsversion() {
    return this.osversion != null;
  }

  public void setOsversionIsSet(boolean value) {
    if (!value) {
      this.osversion = null;
    }
  }

  public String getPhonemodel() {
    return this.phonemodel;
  }

  public DeviceInfo setPhonemodel(String phonemodel) {
    this.phonemodel = phonemodel;
    return this;
  }

  public void unsetPhonemodel() {
    this.phonemodel = null;
  }

  /** Returns true if field phonemodel is set (has been assigned a value) and false otherwise */
  public boolean isSetPhonemodel() {
    return this.phonemodel != null;
  }

  public void setPhonemodelIsSet(boolean value) {
    if (!value) {
      this.phonemodel = null;
    }
  }

  public String getMobile() {
    return this.mobile;
  }

  public DeviceInfo setMobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

  public void unsetMobile() {
    this.mobile = null;
  }

  /** Returns true if field mobile is set (has been assigned a value) and false otherwise */
  public boolean isSetMobile() {
    return this.mobile != null;
  }

  public void setMobileIsSet(boolean value) {
    if (!value) {
      this.mobile = null;
    }
  }

  public String getAaid() {
    return this.aaid;
  }

  public DeviceInfo setAaid(String aaid) {
    this.aaid = aaid;
    return this;
  }

  public void unsetAaid() {
    this.aaid = null;
  }

  /** Returns true if field aaid is set (has been assigned a value) and false otherwise */
  public boolean isSetAaid() {
    return this.aaid != null;
  }

  public void setAaidIsSet(boolean value) {
    if (!value) {
      this.aaid = null;
    }
  }

  public String getAdid() {
    return this.adid;
  }

  public DeviceInfo setAdid(String adid) {
    this.adid = adid;
    return this;
  }

  public void unsetAdid() {
    this.adid = null;
  }

  /** Returns true if field adid is set (has been assigned a value) and false otherwise */
  public boolean isSetAdid() {
    return this.adid != null;
  }

  public void setAdidIsSet(boolean value) {
    if (!value) {
      this.adid = null;
    }
  }

  public String getIdfa() {
    return this.idfa;
  }

  public DeviceInfo setIdfa(String idfa) {
    this.idfa = idfa;
    return this;
  }

  public void unsetIdfa() {
    this.idfa = null;
  }

  /** Returns true if field idfa is set (has been assigned a value) and false otherwise */
  public boolean isSetIdfa() {
    return this.idfa != null;
  }

  public void setIdfaIsSet(boolean value) {
    if (!value) {
      this.idfa = null;
    }
  }

  public String getBrandId() {
    return this.brandId;
  }

  public DeviceInfo setBrandId(String brandId) {
    this.brandId = brandId;
    return this;
  }

  public void unsetBrandId() {
    this.brandId = null;
  }

  /** Returns true if field brandId is set (has been assigned a value) and false otherwise */
  public boolean isSetBrandId() {
    return this.brandId != null;
  }

  public void setBrandIdIsSet(boolean value) {
    if (!value) {
      this.brandId = null;
    }
  }

  public String getBrandName() {
    return this.brandName;
  }

  public DeviceInfo setBrandName(String brandName) {
    this.brandName = brandName;
    return this;
  }

  public void unsetBrandName() {
    this.brandName = null;
  }

  /** Returns true if field brandName is set (has been assigned a value) and false otherwise */
  public boolean isSetBrandName() {
    return this.brandName != null;
  }

  public void setBrandNameIsSet(boolean value) {
    if (!value) {
      this.brandName = null;
    }
  }

  public int getDeviceHeight() {
    return this.deviceHeight;
  }

  public DeviceInfo setDeviceHeight(int deviceHeight) {
    this.deviceHeight = deviceHeight;
    setDeviceHeightIsSet(true);
    return this;
  }

  public void unsetDeviceHeight() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEVICEHEIGHT_ISSET_ID);
  }

  /** Returns true if field deviceHeight is set (has been assigned a value) and false otherwise */
  public boolean isSetDeviceHeight() {
    return EncodingUtils.testBit(__isset_bitfield, __DEVICEHEIGHT_ISSET_ID);
  }

  public void setDeviceHeightIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEVICEHEIGHT_ISSET_ID, value);
  }

  public int getDeviceWidth() {
    return this.deviceWidth;
  }

  public DeviceInfo setDeviceWidth(int deviceWidth) {
    this.deviceWidth = deviceWidth;
    setDeviceWidthIsSet(true);
    return this;
  }

  public void unsetDeviceWidth() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEVICEWIDTH_ISSET_ID);
  }

  /** Returns true if field deviceWidth is set (has been assigned a value) and false otherwise */
  public boolean isSetDeviceWidth() {
    return EncodingUtils.testBit(__isset_bitfield, __DEVICEWIDTH_ISSET_ID);
  }

  public void setDeviceWidthIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEVICEWIDTH_ISSET_ID, value);
  }

  public String getMac() {
    return this.mac;
  }

  public DeviceInfo setMac(String mac) {
    this.mac = mac;
    return this;
  }

  public void unsetMac() {
    this.mac = null;
  }

  /** Returns true if field mac is set (has been assigned a value) and false otherwise */
  public boolean isSetMac() {
    return this.mac != null;
  }

  public void setMacIsSet(boolean value) {
    if (!value) {
      this.mac = null;
    }
  }

  public String getImsi() {
    return this.imsi;
  }

  public DeviceInfo setImsi(String imsi) {
    this.imsi = imsi;
    return this;
  }

  public void unsetImsi() {
    this.imsi = null;
  }

  /** Returns true if field imsi is set (has been assigned a value) and false otherwise */
  public boolean isSetImsi() {
    return this.imsi != null;
  }

  public void setImsiIsSet(boolean value) {
    if (!value) {
      this.imsi = null;
    }
  }

  public String getSerialNo() {
    return this.serialNo;
  }

  public DeviceInfo setSerialNo(String serialNo) {
    this.serialNo = serialNo;
    return this;
  }

  public void unsetSerialNo() {
    this.serialNo = null;
  }

  /** Returns true if field serialNo is set (has been assigned a value) and false otherwise */
  public boolean isSetSerialNo() {
    return this.serialNo != null;
  }

  public void setSerialNoIsSet(boolean value) {
    if (!value) {
      this.serialNo = null;
    }
  }

  public String getDip() {
    return this.dip;
  }

  public DeviceInfo setDip(String dip) {
    this.dip = dip;
    return this;
  }

  public void unsetDip() {
    this.dip = null;
  }

  /** Returns true if field dip is set (has been assigned a value) and false otherwise */
  public boolean isSetDip() {
    return this.dip != null;
  }

  public void setDipIsSet(boolean value) {
    if (!value) {
      this.dip = null;
    }
  }

  public String getDpi() {
    return this.dpi;
  }

  public DeviceInfo setDpi(String dpi) {
    this.dpi = dpi;
    return this;
  }

  public void unsetDpi() {
    this.dpi = null;
  }

  /** Returns true if field dpi is set (has been assigned a value) and false otherwise */
  public boolean isSetDpi() {
    return this.dpi != null;
  }

  public void setDpiIsSet(boolean value) {
    if (!value) {
      this.dpi = null;
    }
  }

  public String getOsVerName() {
	    return this.osVerName;
	  }

  public DeviceInfo setOsVerName(String osVerName) {
    this.osVerName = osVerName;
    return this;
  }

  public void unsetOsVerName() {
    this.osVerName = null;
  }

  /** Returns true if field osVerName is set (has been assigned a value) and false otherwise */
  public boolean isSetOsVerName() {
    return this.osVerName != null;
  }

  public void setOsVerNameIsSet(boolean value) {
    if (!value) {
      this.osVerName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IMEI:
      if (value == null) {
        unsetImei();
      } else {
        setImei((String)value);
      }
      break;

    case OS:
      if (value == null) {
        unsetOs();
      } else {
        setOs((String)value);
      }
      break;

    case OSVERSION:
      if (value == null) {
        unsetOsversion();
      } else {
        setOsversion((String)value);
      }
      break;

    case PHONEMODEL:
      if (value == null) {
        unsetPhonemodel();
      } else {
        setPhonemodel((String)value);
      }
      break;

    case MOBILE:
      if (value == null) {
        unsetMobile();
      } else {
        setMobile((String)value);
      }
      break;

    case AAID:
      if (value == null) {
        unsetAaid();
      } else {
        setAaid((String)value);
      }
      break;

    case ADID:
      if (value == null) {
        unsetAdid();
      } else {
        setAdid((String)value);
      }
      break;

    case IDFA:
      if (value == null) {
        unsetIdfa();
      } else {
        setIdfa((String)value);
      }
      break;

    case BRAND_ID:
      if (value == null) {
        unsetBrandId();
      } else {
        setBrandId((String)value);
      }
      break;

    case BRAND_NAME:
      if (value == null) {
        unsetBrandName();
      } else {
        setBrandName((String)value);
      }
      break;

    case DEVICE_HEIGHT:
      if (value == null) {
        unsetDeviceHeight();
      } else {
        setDeviceHeight((Integer)value);
      }
      break;

    case DEVICE_WIDTH:
      if (value == null) {
        unsetDeviceWidth();
      } else {
        setDeviceWidth((Integer)value);
      }
      break;

    case MAC:
      if (value == null) {
        unsetMac();
      } else {
        setMac((String)value);
      }
      break;

    case IMSI:
      if (value == null) {
        unsetImsi();
      } else {
        setImsi((String)value);
      }
      break;

    case SERIAL_NO:
      if (value == null) {
        unsetSerialNo();
      } else {
        setSerialNo((String)value);
      }
      break;

    case DIP:
      if (value == null) {
        unsetDip();
      } else {
        setDip((String)value);
      }
      break;

    case DPI:
      if (value == null) {
        unsetDpi();
      } else {
        setDpi((String)value);
      }
      break;

    case OS_VER_NAME:
      if (value == null) {
        unsetOsVerName();
      } else {
        setOsVerName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IMEI:
      return getImei();

    case OS:
      return getOs();

    case OSVERSION:
      return getOsversion();

    case PHONEMODEL:
      return getPhonemodel();

    case MOBILE:
      return getMobile();

    case AAID:
      return getAaid();

    case ADID:
      return getAdid();

    case IDFA:
      return getIdfa();

    case BRAND_ID:
      return getBrandId();

    case BRAND_NAME:
      return getBrandName();

    case DEVICE_HEIGHT:
      return Integer.valueOf(getDeviceHeight());

    case DEVICE_WIDTH:
      return Integer.valueOf(getDeviceWidth());

    case MAC:
      return getMac();

    case IMSI:
      return getImsi();

    case SERIAL_NO:
      return getSerialNo();

    case DIP:
      return getDip();

    case DPI:
      return getDpi();

    case OS_VER_NAME:
      return getOsVerName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IMEI:
      return isSetImei();
    case OS:
      return isSetOs();
    case OSVERSION:
      return isSetOsversion();
    case PHONEMODEL:
      return isSetPhonemodel();
    case MOBILE:
      return isSetMobile();
    case AAID:
      return isSetAaid();
    case ADID:
      return isSetAdid();
    case IDFA:
      return isSetIdfa();
    case BRAND_ID:
      return isSetBrandId();
    case BRAND_NAME:
      return isSetBrandName();
    case DEVICE_HEIGHT:
      return isSetDeviceHeight();
    case DEVICE_WIDTH:
      return isSetDeviceWidth();
    case MAC:
      return isSetMac();
    case IMSI:
      return isSetImsi();
    case SERIAL_NO:
      return isSetSerialNo();
    case DIP:
      return isSetDip();
    case DPI:
      return isSetDpi();
    case OS_VER_NAME:
      return isSetOsVerName();
    }
    throw new IllegalStateException();
  }

  
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DeviceInfo)
      return this.equals((DeviceInfo)that);
    return false;
  }

  public boolean equals(DeviceInfo that) {
    if (that == null)
      return false;

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_os = true && this.isSetOs();
    boolean that_present_os = true && that.isSetOs();
    if (this_present_os || that_present_os) {
      if (!(this_present_os && that_present_os))
        return false;
      if (!this.os.equals(that.os))
        return false;
    }

    boolean this_present_osversion = true && this.isSetOsversion();
    boolean that_present_osversion = true && that.isSetOsversion();
    if (this_present_osversion || that_present_osversion) {
      if (!(this_present_osversion && that_present_osversion))
        return false;
      if (!this.osversion.equals(that.osversion))
        return false;
    }

    boolean this_present_phonemodel = true && this.isSetPhonemodel();
    boolean that_present_phonemodel = true && that.isSetPhonemodel();
    if (this_present_phonemodel || that_present_phonemodel) {
      if (!(this_present_phonemodel && that_present_phonemodel))
        return false;
      if (!this.phonemodel.equals(that.phonemodel))
        return false;
    }

    boolean this_present_mobile = true && this.isSetMobile();
    boolean that_present_mobile = true && that.isSetMobile();
    if (this_present_mobile || that_present_mobile) {
      if (!(this_present_mobile && that_present_mobile))
        return false;
      if (!this.mobile.equals(that.mobile))
        return false;
    }

    boolean this_present_aaid = true && this.isSetAaid();
    boolean that_present_aaid = true && that.isSetAaid();
    if (this_present_aaid || that_present_aaid) {
      if (!(this_present_aaid && that_present_aaid))
        return false;
      if (!this.aaid.equals(that.aaid))
        return false;
    }

    boolean this_present_adid = true && this.isSetAdid();
    boolean that_present_adid = true && that.isSetAdid();
    if (this_present_adid || that_present_adid) {
      if (!(this_present_adid && that_present_adid))
        return false;
      if (!this.adid.equals(that.adid))
        return false;
    }

    boolean this_present_idfa = true && this.isSetIdfa();
    boolean that_present_idfa = true && that.isSetIdfa();
    if (this_present_idfa || that_present_idfa) {
      if (!(this_present_idfa && that_present_idfa))
        return false;
      if (!this.idfa.equals(that.idfa))
        return false;
    }

    boolean this_present_brandId = true && this.isSetBrandId();
    boolean that_present_brandId = true && that.isSetBrandId();
    if (this_present_brandId || that_present_brandId) {
      if (!(this_present_brandId && that_present_brandId))
        return false;
      if (!this.brandId.equals(that.brandId))
        return false;
    }

    boolean this_present_brandName = true && this.isSetBrandName();
    boolean that_present_brandName = true && that.isSetBrandName();
    if (this_present_brandName || that_present_brandName) {
      if (!(this_present_brandName && that_present_brandName))
        return false;
      if (!this.brandName.equals(that.brandName))
        return false;
    }

    boolean this_present_deviceHeight = true && this.isSetDeviceHeight();
    boolean that_present_deviceHeight = true && that.isSetDeviceHeight();
    if (this_present_deviceHeight || that_present_deviceHeight) {
      if (!(this_present_deviceHeight && that_present_deviceHeight))
        return false;
      if (this.deviceHeight != that.deviceHeight)
        return false;
    }

    boolean this_present_deviceWidth = true && this.isSetDeviceWidth();
    boolean that_present_deviceWidth = true && that.isSetDeviceWidth();
    if (this_present_deviceWidth || that_present_deviceWidth) {
      if (!(this_present_deviceWidth && that_present_deviceWidth))
        return false;
      if (this.deviceWidth != that.deviceWidth)
        return false;
    }

    boolean this_present_mac = true && this.isSetMac();
    boolean that_present_mac = true && that.isSetMac();
    if (this_present_mac || that_present_mac) {
      if (!(this_present_mac && that_present_mac))
        return false;
      if (!this.mac.equals(that.mac))
        return false;
    }

    boolean this_present_imsi = true && this.isSetImsi();
    boolean that_present_imsi = true && that.isSetImsi();
    if (this_present_imsi || that_present_imsi) {
      if (!(this_present_imsi && that_present_imsi))
        return false;
      if (!this.imsi.equals(that.imsi))
        return false;
    }

    boolean this_present_serialNo = true && this.isSetSerialNo();
    boolean that_present_serialNo = true && that.isSetSerialNo();
    if (this_present_serialNo || that_present_serialNo) {
      if (!(this_present_serialNo && that_present_serialNo))
        return false;
      if (!this.serialNo.equals(that.serialNo))
        return false;
    }

    boolean this_present_dip = true && this.isSetDip();
    boolean that_present_dip = true && that.isSetDip();
    if (this_present_dip || that_present_dip) {
      if (!(this_present_dip && that_present_dip))
        return false;
      if (!this.dip.equals(that.dip))
        return false;
    }

    boolean this_present_dpi = true && this.isSetDpi();
    boolean that_present_dpi = true && that.isSetDpi();
    if (this_present_dpi || that_present_dpi) {
      if (!(this_present_dpi && that_present_dpi))
        return false;
      if (!this.dpi.equals(that.dpi))
        return false;
    }

    boolean this_present_osVerName = true && this.isSetOsVerName();
    boolean that_present_osVerName = true && that.isSetOsVerName();
    if (this_present_osVerName || that_present_osVerName) {
      if (!(this_present_osVerName && that_present_osVerName))
        return false;
      if (!this.osVerName.equals(that.osVerName))
        return false;
    }

    return true;
  }

  
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_imei = true && (isSetImei());
    list.add(present_imei);
    if (present_imei)
      list.add(imei);

    boolean present_os = true && (isSetOs());
    list.add(present_os);
    if (present_os)
      list.add(os);

    boolean present_osversion = true && (isSetOsversion());
    list.add(present_osversion);
    if (present_osversion)
      list.add(osversion);

    boolean present_phonemodel = true && (isSetPhonemodel());
    list.add(present_phonemodel);
    if (present_phonemodel)
      list.add(phonemodel);

    boolean present_mobile = true && (isSetMobile());
    list.add(present_mobile);
    if (present_mobile)
      list.add(mobile);

    boolean present_aaid = true && (isSetAaid());
    list.add(present_aaid);
    if (present_aaid)
      list.add(aaid);

    boolean present_adid = true && (isSetAdid());
    list.add(present_adid);
    if (present_adid)
      list.add(adid);

    boolean present_idfa = true && (isSetIdfa());
    list.add(present_idfa);
    if (present_idfa)
      list.add(idfa);

    boolean present_brandId = true && (isSetBrandId());
    list.add(present_brandId);
    if (present_brandId)
      list.add(brandId);

    boolean present_brandName = true && (isSetBrandName());
    list.add(present_brandName);
    if (present_brandName)
      list.add(brandName);

    boolean present_deviceHeight = true && (isSetDeviceHeight());
    list.add(present_deviceHeight);
    if (present_deviceHeight)
      list.add(deviceHeight);

    boolean present_deviceWidth = true && (isSetDeviceWidth());
    list.add(present_deviceWidth);
    if (present_deviceWidth)
      list.add(deviceWidth);

    boolean present_mac = true && (isSetMac());
    list.add(present_mac);
    if (present_mac)
      list.add(mac);

    boolean present_imsi = true && (isSetImsi());
    list.add(present_imsi);
    if (present_imsi)
      list.add(imsi);

    boolean present_serialNo = true && (isSetSerialNo());
    list.add(present_serialNo);
    if (present_serialNo)
      list.add(serialNo);

    boolean present_dip = true && (isSetDip());
    list.add(present_dip);
    if (present_dip)
      list.add(dip);

    boolean present_dpi = true && (isSetDpi());
    list.add(present_dpi);
    if (present_dpi)
      list.add(dpi);

    boolean present_osVerName = true && (isSetOsVerName());
    list.add(present_osVerName);
    if (present_osVerName)
      list.add(osVerName);

    return list.hashCode();
  }

  
  public int compareTo(DeviceInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetImei()).compareTo(other.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imei, other.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOs()).compareTo(other.isSetOs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.os, other.os);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOsversion()).compareTo(other.isSetOsversion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOsversion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.osversion, other.osversion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPhonemodel()).compareTo(other.isSetPhonemodel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPhonemodel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.phonemodel, other.phonemodel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMobile()).compareTo(other.isSetMobile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMobile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mobile, other.mobile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAaid()).compareTo(other.isSetAaid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAaid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aaid, other.aaid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdid()).compareTo(other.isSetAdid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adid, other.adid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIdfa()).compareTo(other.isSetIdfa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdfa()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idfa, other.idfa);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBrandId()).compareTo(other.isSetBrandId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrandId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brandId, other.brandId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBrandName()).compareTo(other.isSetBrandName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrandName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brandName, other.brandName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDeviceHeight()).compareTo(other.isSetDeviceHeight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeviceHeight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deviceHeight, other.deviceHeight);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDeviceWidth()).compareTo(other.isSetDeviceWidth());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeviceWidth()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deviceWidth, other.deviceWidth);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMac()).compareTo(other.isSetMac());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMac()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mac, other.mac);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImsi()).compareTo(other.isSetImsi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImsi()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imsi, other.imsi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSerialNo()).compareTo(other.isSetSerialNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSerialNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.serialNo, other.serialNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDip()).compareTo(other.isSetDip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dip, other.dip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDpi()).compareTo(other.isSetDpi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDpi()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dpi, other.dpi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOsVerName()).compareTo(other.isSetOsVerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOsVerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.osVerName, other.osVerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  
  public String toString() {
    StringBuilder sb = new StringBuilder("DeviceInfo(");
    boolean first = true;

    if (isSetImei()) {
      sb.append("imei:");
      if (this.imei == null) {
        sb.append("null");
      } else {
        sb.append(this.imei);
      }
      first = false;
    }
    if (isSetOs()) {
      if (!first) sb.append(", ");
      sb.append("os:");
      if (this.os == null) {
        sb.append("null");
      } else {
        sb.append(this.os);
      }
      first = false;
    }
    if (isSetOsversion()) {
      if (!first) sb.append(", ");
      sb.append("osversion:");
      if (this.osversion == null) {
        sb.append("null");
      } else {
        sb.append(this.osversion);
      }
      first = false;
    }
    if (isSetPhonemodel()) {
      if (!first) sb.append(", ");
      sb.append("phonemodel:");
      if (this.phonemodel == null) {
        sb.append("null");
      } else {
        sb.append(this.phonemodel);
      }
      first = false;
    }
    if (isSetMobile()) {
      if (!first) sb.append(", ");
      sb.append("mobile:");
      if (this.mobile == null) {
        sb.append("null");
      } else {
        sb.append(this.mobile);
      }
      first = false;
    }
    if (isSetAaid()) {
      if (!first) sb.append(", ");
      sb.append("aaid:");
      if (this.aaid == null) {
        sb.append("null");
      } else {
        sb.append(this.aaid);
      }
      first = false;
    }
    if (isSetAdid()) {
      if (!first) sb.append(", ");
      sb.append("adid:");
      if (this.adid == null) {
        sb.append("null");
      } else {
        sb.append(this.adid);
      }
      first = false;
    }
    if (isSetIdfa()) {
      if (!first) sb.append(", ");
      sb.append("idfa:");
      if (this.idfa == null) {
        sb.append("null");
      } else {
        sb.append(this.idfa);
      }
      first = false;
    }
    if (isSetBrandId()) {
      if (!first) sb.append(", ");
      sb.append("brandId:");
      if (this.brandId == null) {
        sb.append("null");
      } else {
        sb.append(this.brandId);
      }
      first = false;
    }
    if (isSetBrandName()) {
      if (!first) sb.append(", ");
      sb.append("brandName:");
      if (this.brandName == null) {
        sb.append("null");
      } else {
        sb.append(this.brandName);
      }
      first = false;
    }
    if (isSetDeviceHeight()) {
      if (!first) sb.append(", ");
      sb.append("deviceHeight:");
      sb.append(this.deviceHeight);
      first = false;
    }
    if (isSetDeviceWidth()) {
      if (!first) sb.append(", ");
      sb.append("deviceWidth:");
      sb.append(this.deviceWidth);
      first = false;
    }
    if (isSetMac()) {
      if (!first) sb.append(", ");
      sb.append("mac:");
      if (this.mac == null) {
        sb.append("null");
      } else {
        sb.append(this.mac);
      }
      first = false;
    }
    if (isSetImsi()) {
      if (!first) sb.append(", ");
      sb.append("imsi:");
      if (this.imsi == null) {
        sb.append("null");
      } else {
        sb.append(this.imsi);
      }
      first = false;
    }
    if (isSetSerialNo()) {
      if (!first) sb.append(", ");
      sb.append("serialNo:");
      if (this.serialNo == null) {
        sb.append("null");
      } else {
        sb.append(this.serialNo);
      }
      first = false;
    }
    if (isSetDip()) {
      if (!first) sb.append(", ");
      sb.append("dip:");
      if (this.dip == null) {
        sb.append("null");
      } else {
        sb.append(this.dip);
      }
      first = false;
    }
    if (isSetDpi()) {
      if (!first) sb.append(", ");
      sb.append("dpi:");
      if (this.dpi == null) {
        sb.append("null");
      } else {
        sb.append(this.dpi);
      }
      first = false;
    }
    if (isSetOsVerName()) {
      if (!first) sb.append(", ");
      sb.append("osVerName:");
      if (this.osVerName == null) {
        sb.append("null");
      } else {
        sb.append(this.osVerName);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DeviceInfoStandardSchemeFactory implements SchemeFactory {
    public DeviceInfoStandardScheme getScheme() {
      return new DeviceInfoStandardScheme();
    }
  }

  private static class DeviceInfoStandardScheme extends StandardScheme<DeviceInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DeviceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IMEI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imei = iprot.readString();
              struct.setImeiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.os = iprot.readString();
              struct.setOsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OSVERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.osversion = iprot.readString();
              struct.setOsversionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PHONEMODEL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.phonemodel = iprot.readString();
              struct.setPhonemodelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // MOBILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mobile = iprot.readString();
              struct.setMobileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // AAID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.aaid = iprot.readString();
              struct.setAaidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ADID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adid = iprot.readString();
              struct.setAdidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IDFA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.idfa = iprot.readString();
              struct.setIdfaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // BRAND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.brandId = iprot.readString();
              struct.setBrandIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // BRAND_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.brandName = iprot.readString();
              struct.setBrandNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // DEVICE_HEIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.deviceHeight = iprot.readI32();
              struct.setDeviceHeightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // DEVICE_WIDTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.deviceWidth = iprot.readI32();
              struct.setDeviceWidthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // MAC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mac = iprot.readString();
              struct.setMacIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // IMSI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imsi = iprot.readString();
              struct.setImsiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // SERIAL_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.serialNo = iprot.readString();
              struct.setSerialNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // DIP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dip = iprot.readString();
              struct.setDipIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // DPI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dpi = iprot.readString();
              struct.setDpiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 18: // OS_VER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.osVerName = iprot.readString();
              struct.setOsVerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DeviceInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.imei != null) {
        if (struct.isSetImei()) {
          oprot.writeFieldBegin(IMEI_FIELD_DESC);
          oprot.writeString(struct.imei);
          oprot.writeFieldEnd();
        }
      }
      if (struct.os != null) {
        if (struct.isSetOs()) {
          oprot.writeFieldBegin(OS_FIELD_DESC);
          oprot.writeString(struct.os);
          oprot.writeFieldEnd();
        }
      }
      if (struct.osversion != null) {
        if (struct.isSetOsversion()) {
          oprot.writeFieldBegin(OSVERSION_FIELD_DESC);
          oprot.writeString(struct.osversion);
          oprot.writeFieldEnd();
        }
      }
      if (struct.phonemodel != null) {
        if (struct.isSetPhonemodel()) {
          oprot.writeFieldBegin(PHONEMODEL_FIELD_DESC);
          oprot.writeString(struct.phonemodel);
          oprot.writeFieldEnd();
        }
      }
      if (struct.mobile != null) {
        if (struct.isSetMobile()) {
          oprot.writeFieldBegin(MOBILE_FIELD_DESC);
          oprot.writeString(struct.mobile);
          oprot.writeFieldEnd();
        }
      }
      if (struct.aaid != null) {
        if (struct.isSetAaid()) {
          oprot.writeFieldBegin(AAID_FIELD_DESC);
          oprot.writeString(struct.aaid);
          oprot.writeFieldEnd();
        }
      }
      if (struct.adid != null) {
        if (struct.isSetAdid()) {
          oprot.writeFieldBegin(ADID_FIELD_DESC);
          oprot.writeString(struct.adid);
          oprot.writeFieldEnd();
        }
      }
      if (struct.idfa != null) {
        if (struct.isSetIdfa()) {
          oprot.writeFieldBegin(IDFA_FIELD_DESC);
          oprot.writeString(struct.idfa);
          oprot.writeFieldEnd();
        }
      }
      if (struct.brandId != null) {
        if (struct.isSetBrandId()) {
          oprot.writeFieldBegin(BRAND_ID_FIELD_DESC);
          oprot.writeString(struct.brandId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.brandName != null) {
        if (struct.isSetBrandName()) {
          oprot.writeFieldBegin(BRAND_NAME_FIELD_DESC);
          oprot.writeString(struct.brandName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetDeviceHeight()) {
        oprot.writeFieldBegin(DEVICE_HEIGHT_FIELD_DESC);
        oprot.writeI32(struct.deviceHeight);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDeviceWidth()) {
        oprot.writeFieldBegin(DEVICE_WIDTH_FIELD_DESC);
        oprot.writeI32(struct.deviceWidth);
        oprot.writeFieldEnd();
      }
      if (struct.mac != null) {
        if (struct.isSetMac()) {
          oprot.writeFieldBegin(MAC_FIELD_DESC);
          oprot.writeString(struct.mac);
          oprot.writeFieldEnd();
        }
      }
      if (struct.imsi != null) {
        if (struct.isSetImsi()) {
          oprot.writeFieldBegin(IMSI_FIELD_DESC);
          oprot.writeString(struct.imsi);
          oprot.writeFieldEnd();
        }
      }
      if (struct.serialNo != null) {
        if (struct.isSetSerialNo()) {
          oprot.writeFieldBegin(SERIAL_NO_FIELD_DESC);
          oprot.writeString(struct.serialNo);
          oprot.writeFieldEnd();
        }
      }
      if (struct.dip != null) {
        if (struct.isSetDip()) {
          oprot.writeFieldBegin(DIP_FIELD_DESC);
          oprot.writeString(struct.dip);
          oprot.writeFieldEnd();
        }
      }
      if (struct.dpi != null) {
        if (struct.isSetDpi()) {
          oprot.writeFieldBegin(DPI_FIELD_DESC);
          oprot.writeString(struct.dpi);
          oprot.writeFieldEnd();
        }
      }
      if (struct.osVerName != null) {
        if (struct.isSetOsVerName()) {
          oprot.writeFieldBegin(OS_VER_NAME_FIELD_DESC);
          oprot.writeString(struct.osVerName);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DeviceInfoTupleSchemeFactory implements SchemeFactory {
    public DeviceInfoTupleScheme getScheme() {
      return new DeviceInfoTupleScheme();
    }
  }

  private static class DeviceInfoTupleScheme extends TupleScheme<DeviceInfo> {

    
    public void write(org.apache.thrift.protocol.TProtocol prot, DeviceInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetImei()) {
        optionals.set(0);
      }
      if (struct.isSetOs()) {
        optionals.set(1);
      }
      if (struct.isSetOsversion()) {
        optionals.set(2);
      }
      if (struct.isSetPhonemodel()) {
        optionals.set(3);
      }
      if (struct.isSetMobile()) {
        optionals.set(4);
      }
      if (struct.isSetAaid()) {
        optionals.set(5);
      }
      if (struct.isSetAdid()) {
        optionals.set(6);
      }
      if (struct.isSetIdfa()) {
        optionals.set(7);
      }
      if (struct.isSetBrandId()) {
        optionals.set(8);
      }
      if (struct.isSetBrandName()) {
        optionals.set(9);
      }
      if (struct.isSetDeviceHeight()) {
        optionals.set(10);
      }
      if (struct.isSetDeviceWidth()) {
        optionals.set(11);
      }
      if (struct.isSetMac()) {
        optionals.set(12);
      }
      if (struct.isSetImsi()) {
        optionals.set(13);
      }
      if (struct.isSetSerialNo()) {
        optionals.set(14);
      }
      if (struct.isSetDip()) {
        optionals.set(15);
      }
      if (struct.isSetDpi()) {
        optionals.set(16);
      }
      if (struct.isSetOsVerName()) {
        optionals.set(17);
      }
      oprot.writeBitSet(optionals, 18);
      if (struct.isSetImei()) {
        oprot.writeString(struct.imei);
      }
      if (struct.isSetOs()) {
        oprot.writeString(struct.os);
      }
      if (struct.isSetOsversion()) {
        oprot.writeString(struct.osversion);
      }
      if (struct.isSetPhonemodel()) {
        oprot.writeString(struct.phonemodel);
      }
      if (struct.isSetMobile()) {
        oprot.writeString(struct.mobile);
      }
      if (struct.isSetAaid()) {
        oprot.writeString(struct.aaid);
      }
      if (struct.isSetAdid()) {
        oprot.writeString(struct.adid);
      }
      if (struct.isSetIdfa()) {
        oprot.writeString(struct.idfa);
      }
      if (struct.isSetBrandId()) {
        oprot.writeString(struct.brandId);
      }
      if (struct.isSetBrandName()) {
        oprot.writeString(struct.brandName);
      }
      if (struct.isSetDeviceHeight()) {
        oprot.writeI32(struct.deviceHeight);
      }
      if (struct.isSetDeviceWidth()) {
        oprot.writeI32(struct.deviceWidth);
      }
      if (struct.isSetMac()) {
        oprot.writeString(struct.mac);
      }
      if (struct.isSetImsi()) {
        oprot.writeString(struct.imsi);
      }
      if (struct.isSetSerialNo()) {
        oprot.writeString(struct.serialNo);
      }
      if (struct.isSetDip()) {
        oprot.writeString(struct.dip);
      }
      if (struct.isSetDpi()) {
        oprot.writeString(struct.dpi);
      }
      if (struct.isSetOsVerName()) {
        oprot.writeString(struct.osVerName);
      }
    }

    
    public void read(org.apache.thrift.protocol.TProtocol prot, DeviceInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(18);
      if (incoming.get(0)) {
        struct.imei = iprot.readString();
        struct.setImeiIsSet(true);
      }
      if (incoming.get(1)) {
        struct.os = iprot.readString();
        struct.setOsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.osversion = iprot.readString();
        struct.setOsversionIsSet(true);
      }
      if (incoming.get(3)) {
        struct.phonemodel = iprot.readString();
        struct.setPhonemodelIsSet(true);
      }
      if (incoming.get(4)) {
        struct.mobile = iprot.readString();
        struct.setMobileIsSet(true);
      }
      if (incoming.get(5)) {
        struct.aaid = iprot.readString();
        struct.setAaidIsSet(true);
      }
      if (incoming.get(6)) {
        struct.adid = iprot.readString();
        struct.setAdidIsSet(true);
      }
      if (incoming.get(7)) {
        struct.idfa = iprot.readString();
        struct.setIdfaIsSet(true);
      }
      if (incoming.get(8)) {
        struct.brandId = iprot.readString();
        struct.setBrandIdIsSet(true);
      }
      if (incoming.get(9)) {
        struct.brandName = iprot.readString();
        struct.setBrandNameIsSet(true);
      }
      if (incoming.get(10)) {
        struct.deviceHeight = iprot.readI32();
        struct.setDeviceHeightIsSet(true);
      }
      if (incoming.get(11)) {
        struct.deviceWidth = iprot.readI32();
        struct.setDeviceWidthIsSet(true);
      }
      if (incoming.get(12)) {
        struct.mac = iprot.readString();
        struct.setMacIsSet(true);
      }
      if (incoming.get(13)) {
        struct.imsi = iprot.readString();
        struct.setImsiIsSet(true);
      }
      if (incoming.get(14)) {
        struct.serialNo = iprot.readString();
        struct.setSerialNoIsSet(true);
      }
      if (incoming.get(15)) {
        struct.dip = iprot.readString();
        struct.setDipIsSet(true);
      }
      if (incoming.get(16)) {
        struct.dpi = iprot.readString();
        struct.setDpiIsSet(true);
      }
      if (incoming.get(17)) {
        struct.osVerName = iprot.readString();
        struct.setOsVerNameIsSet(true);
      }
    }
  }

}

