/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.app.dis.proxy.thrift.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JoinSource implements org.apache.thrift.TEnum {
  TENCENT_QQDOWNLOADER(1),
  BAIDU_APPSEARCH(2),
  QIHOO_APPSTORE(3),
  WANDOUJIA_PHOENIX2(4),
  XIAOMI_MARKET(5),
  HUAWEI_APPMARKET(6),
  DRAGON_PANDASPACE(7),
  HIAPK_MARKETPHO(8),
  YINGYONGHUI_MARKET(9),
  TENCENT_QQPIMSECURE(10),
  MAPPN_GFAN(11),
  PP_ASSISTANT(12),
  OPPO_MARKET(13),
  GOAPK_MARKET(14),
  ZTE_MARKET(15),
  YULONG_COOLMART(16),
  LENOVO_LEOS_APPSTORE(17),
  COOLAPK_MARKET(18),
  SOGOU_ZHUSHOU(19),
  WANKA_APPSTORE(20),
  ONEMOBI_APPSTORE(21),
  ANZHI_APPSTORE(22),
  WANGXIANG_APPSTORE(23),
  HAIQIBING_APPSTORE(24),
  QIHOO_TYPE2_APPSTORE(25),
  QUQUANSU_APPSTORE(26),
  YITONG_APPSTORE(27),
  YOURAN_APPSTORE(28),
  DALUOMA_APPSTORE(29),
  WANYUJIUXIN_APPSTORE(30),
  YOURAN_TYPE2_APPSTORE(31),
  BAIDUBAITONG_APPSTORE(32),
  TIANMEI_APPSTORE(33),
  MILIANG_APPSTORE(34),
  QUYUANSU2_APPSTORE(35),
  YOUYOU_APPSTORE(36),
  ZS_APPSTORE(37);

  private final int value;

  private JoinSource(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JoinSource findByValue(int value) { 
    switch (value) {
      case 1:
        return TENCENT_QQDOWNLOADER;
      case 2:
        return BAIDU_APPSEARCH;
      case 3:
        return QIHOO_APPSTORE;
      case 4:
        return WANDOUJIA_PHOENIX2;
      case 5:
        return XIAOMI_MARKET;
      case 6:
        return HUAWEI_APPMARKET;
      case 7:
        return DRAGON_PANDASPACE;
      case 8:
        return HIAPK_MARKETPHO;
      case 9:
        return YINGYONGHUI_MARKET;
      case 10:
        return TENCENT_QQPIMSECURE;
      case 11:
        return MAPPN_GFAN;
      case 12:
        return PP_ASSISTANT;
      case 13:
        return OPPO_MARKET;
      case 14:
        return GOAPK_MARKET;
      case 15:
        return ZTE_MARKET;
      case 16:
        return YULONG_COOLMART;
      case 17:
        return LENOVO_LEOS_APPSTORE;
      case 18:
        return COOLAPK_MARKET;
      case 19:
        return SOGOU_ZHUSHOU;
      case 20:
        return WANKA_APPSTORE;
      case 21:
        return ONEMOBI_APPSTORE;
      case 22:
        return ANZHI_APPSTORE;
      case 23:
        return WANGXIANG_APPSTORE;
      case 24:
        return HAIQIBING_APPSTORE;
      case 25:
        return QIHOO_TYPE2_APPSTORE;
      case 26:
        return QUQUANSU_APPSTORE;
      case 27:
        return YITONG_APPSTORE;
      case 28:
        return YOURAN_APPSTORE;
      case 29:
        return DALUOMA_APPSTORE;
      case 30:
        return WANYUJIUXIN_APPSTORE;
      case 31:
        return YOURAN_TYPE2_APPSTORE;
      case 32:
        return BAIDUBAITONG_APPSTORE;
      case 33:
        return TIANMEI_APPSTORE;
      case 34:
        return MILIANG_APPSTORE;
      case 35:
        return QUYUANSU2_APPSTORE;
      case 36:
        return YOUYOU_APPSTORE;
      case 37:
        return ZS_APPSTORE;
      default:
        return null;
    }
  }
}
